// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SerializationTest.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DarkSideOfSerialization.Proto {

  /// <summary>Holder for reflection information generated from SerializationTest.proto</summary>
  public static partial class SerializationTestReflection {

    #region Descriptor
    /// <summary>File descriptor for SerializationTest.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SerializationTestReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdTZXJpYWxpemF0aW9uVGVzdC5wcm90bxIRU2VyaWFsaXphdGlvblRlc3Qi",
            "NQoEVGVzdBIXCg9zdHJpbmdfcHJvcGVydHkYASABKAkSFAoMaW50X3Byb3Bl",
            "cnR5GAIgASgFQiCqAh1EYXJrU2lkZU9mU2VyaWFsaXphdGlvbi5Qcm90b2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DarkSideOfSerialization.Proto.Test), global::DarkSideOfSerialization.Proto.Test.Parser, new[]{ "StringProperty", "IntProperty" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Test : pb::IMessage<Test> {
    private static readonly pb::MessageParser<Test> _parser = new pb::MessageParser<Test>(() => new Test());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Test> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DarkSideOfSerialization.Proto.SerializationTestReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Test() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Test(Test other) : this() {
      stringProperty_ = other.stringProperty_;
      intProperty_ = other.intProperty_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Test Clone() {
      return new Test(this);
    }

    /// <summary>Field number for the "string_property" field.</summary>
    public const int StringPropertyFieldNumber = 1;
    private string stringProperty_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string StringProperty {
      get { return stringProperty_; }
      set {
        stringProperty_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "int_property" field.</summary>
    public const int IntPropertyFieldNumber = 2;
    private int intProperty_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IntProperty {
      get { return intProperty_; }
      set {
        intProperty_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Test);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Test other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (StringProperty != other.StringProperty) return false;
      if (IntProperty != other.IntProperty) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (StringProperty.Length != 0) hash ^= StringProperty.GetHashCode();
      if (IntProperty != 0) hash ^= IntProperty.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (StringProperty.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(StringProperty);
      }
      if (IntProperty != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(IntProperty);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (StringProperty.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(StringProperty);
      }
      if (IntProperty != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IntProperty);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Test other) {
      if (other == null) {
        return;
      }
      if (other.StringProperty.Length != 0) {
        StringProperty = other.StringProperty;
      }
      if (other.IntProperty != 0) {
        IntProperty = other.IntProperty;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            StringProperty = input.ReadString();
            break;
          }
          case 16: {
            IntProperty = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
